// <auto-generated />
using System;
using FoxClub.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoxClub.Migrations
{
    [DbContext(typeof(FoxClubDbContext))]
    [Migration("20200423133349_add-migration initialDBSet")]
    partial class addmigrationinitialDBSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoxClub.Models.Fox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foxes");
                });

            modelBuilder.Entity("FoxClub.Models.Nutrition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Food")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FoxId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoxId");

                    b.ToTable("Nutritions");
                });

            modelBuilder.Entity("FoxClub.Models.Trick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FoxId")
                        .HasColumnType("int");

                    b.Property<string>("NameTrick")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoxId");

                    b.ToTable("Tricks");
                });

            modelBuilder.Entity("FoxClub.Models.Nutrition", b =>
                {
                    b.HasOne("FoxClub.Models.Fox", "Fox")
                        .WithMany()
                        .HasForeignKey("FoxId");
                });

            modelBuilder.Entity("FoxClub.Models.Trick", b =>
                {
                    b.HasOne("FoxClub.Models.Fox", "Fox")
                        .WithMany()
                        .HasForeignKey("FoxId");
                });
#pragma warning restore 612, 618
        }
    }
}
